[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmd = "rm -rf node_modules package-lock.json && npm install --include=optional --verbose"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_OPTIONAL = "true"
